# Generated by Django 3.0.3 on 2020-06-01 03:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('modified_date', models.DateTimeField(default=datetime.datetime(2020, 5, 31, 23, 48, 58, 936945))),
            ],
            options={
                'db_table': 'person_table',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], default='Full Time', max_length=15)),
                ('designation', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=350)),
                ('modified_date', models.DateTimeField(default=datetime.datetime(2020, 5, 31, 23, 48, 58, 938943))),
                ('row_ref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_web.Person')),
            ],
            options={
                'db_table': 'work_table',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_per_level', models.CharField(max_length=100)),
                ('skill_proficiency', models.CharField(max_length=100)),
                ('modified_date', models.DateTimeField(default=datetime.datetime(2020, 5, 31, 23, 48, 58, 938943))),
                ('row_ref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_web.Person')),
            ],
            options={
                'db_table': 'skills_table',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('inst_name', models.CharField(max_length=100)),
                ('completion_yr', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], default='full time', max_length=15)),
                ('description', models.CharField(max_length=350)),
                ('modified_date', models.DateTimeField(default=datetime.datetime(2020, 5, 31, 23, 48, 58, 937943))),
                ('row_ref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_web.Person')),
            ],
            options={
                'db_table': 'edu_table',
            },
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_head', models.CharField(max_length=70)),
                ('info_detail', models.CharField(max_length=250)),
                ('modified_date', models.DateTimeField(default=datetime.datetime(2020, 5, 31, 23, 48, 58, 937943))),
                ('row_ref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_web.Person')),
            ],
            options={
                'db_table': 'details_table',
            },
        ),
    ]
