# Generated by Django 3.0.3 on 2020-06-01 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 23, 49, 32, 995925)),
        ),
        migrations.AlterField(
            model_name='education',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 23, 49, 32, 996922)),
        ),
        migrations.AlterField(
            model_name='person',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 23, 49, 32, 995925)),
        ),
        migrations.AlterField(
            model_name='skills',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 23, 49, 32, 997950)),
        ),
        migrations.AlterField(
            model_name='work',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 23, 49, 32, 996922)),
        ),
    ]
