# Generated by Django 3.0.3 on 2020-06-04 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_web', '0005_auto_20200604_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 13, 37, 16, 547775)),
        ),
        migrations.AlterField(
            model_name='education',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 13, 37, 16, 549771)),
        ),
        migrations.AlterField(
            model_name='person',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 13, 37, 16, 546919)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 13, 37, 16, 554754)),
        ),
        migrations.AlterField(
            model_name='skills',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 13, 37, 16, 553757)),
        ),
        migrations.AlterField(
            model_name='work',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 13, 37, 16, 551762)),
        ),
    ]
