# Generated by Django 3.0.3 on 2020-06-06 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_web', '0006_auto_20200604_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 15, 18, 17, 749308)),
        ),
        migrations.AlterField(
            model_name='education',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 15, 18, 17, 750336)),
        ),
        migrations.AlterField(
            model_name='person',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 15, 18, 17, 748344)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 15, 18, 17, 752298)),
        ),
        migrations.AlterField(
            model_name='skills',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 15, 18, 17, 751301)),
        ),
        migrations.AlterField(
            model_name='work',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 15, 18, 17, 750336)),
        ),
    ]
