# Generated by Django 3.0.3 on 2020-06-06 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_web', '0007_auto_20200606_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 15, 22, 33, 73682)),
        ),
        migrations.AlterField(
            model_name='education',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 15, 22, 33, 73682)),
        ),
        migrations.AlterField(
            model_name='person',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 15, 22, 33, 73258)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 15, 22, 33, 76676)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_image',
            field=models.FileField(blank=True, upload_to='project/'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 15, 22, 33, 75678)),
        ),
        migrations.AlterField(
            model_name='work',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 15, 22, 33, 74680)),
        ),
    ]
