# Generated by Django 3.0.3 on 2020-06-16 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_web', '0008_auto_20200606_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 19, 15, 17, 588375)),
        ),
        migrations.AlterField(
            model_name='education',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 19, 15, 17, 588375)),
        ),
        migrations.AlterField(
            model_name='person',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 19, 15, 17, 588375)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 19, 15, 17, 588375)),
        ),
        migrations.AlterField(
            model_name='skills',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 19, 15, 17, 588375)),
        ),
        migrations.AlterField(
            model_name='work',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 19, 15, 17, 588375)),
        ),
    ]
